const script = [
  `An explosion rocks the ship as two robots, Artoo-Detoo (R2- D2) and See-Threepio (C-3PO) struggle to make their way through the shaking, bouncing passageway. Both robots are old and battered. Artoo is a short, claw-armed tripod. His face is a mass of computer lights surrounding a radar eye. Threepio, on the other hand, is a tall, slender robot of 
human proportions. He has a gleaming bronze-like metallic surface of an Art Deco design.`,
  `The nervous Rebel troopers aim their weapons. Suddenly a tremendous blast opens up a hole in the main passageway and a score of fearsome armored spacesuited stormtroopers make their way into the smoke-filled corridor.In a few minutes the entire passageway is ablaze with laserfire. The deadly bolts ricochet in wild random patterns creating huge explosions. Stormtroopers scatter and duck behind storage lockers. Laserbolts hit several Rebel soldiers who scream and stagger through the smoke, holding shattered arms and faces`,
  `A light wind whips at him as he adjusts several valves on a large battered moisture vaporator which sticks out of the desert floor much like an oil pipe with valves. He is aided by a beatup tread-robot with six claw arms. The little robot appears to be barely functioning and moves with jerky motions. A bright sparkle in the morning sky catches Luke's 
eye and he instinctively grabs a pair of electrobinoculars from his utility belt. He stands transfixed for a few moments studying the heavens, then dashed toward his dented, crudely repaired Landspeeder (an auto-like transport that travels a few feet above the ground on a magnetic-field). He motions for the tiny robot to follow him.`,
  `LUKE: Hurry up! Come with me! What are you waiting for?! Get in gear! The robot scoots around in a tight circle, stops short, and smoke begins to pour out of every joint. Luke throws his arms up in disgust. Exasperated, the young farm boy jumps into his Landspeeder leavingthesmoldering robot to hum madly.`,
  `The evil Darth Vader stands amid the broken and twisted bodies of his foes. He grabs a wounded Rebel Officer by the neck as an Imperial Officer rushes up to the Dark Lord.The Death Star plans are not in the main computer.Vader squeezes the neck of the Rebel Officer, who struggles in vain.The Rebel refuses to speak but eventually cries out as the Dark Lord begins to squeeze the officer's throat, creating a gruesome snapping and choking, until the soldier goes limp. Vader tosses the dead soldier against the wall and turns to his troops`,
  `A Star Destroyer moves through space, releasing Imperial probe robots from its underside One of these probes zooms toward the planet Hoth and lands on its ice- covered surface. An explosion marks the point of impact. A weird mechanical sound rises above the whining of the 
  wind. A strange probe robot, with several extended sensors,emerges from the smoke-shrouded crater. The ominous mechanical probe floats across the snow plain and disappears into the distance. A small figure gallops across the windswept ice slope. The bundled rider is mounted on a large gray snow lizard, a Tauntaun. Curving plumes of snow rise from beneath the speeding paws of the two-legged beast.`,
  `HAN:Well, the bounty hunter we ran into on Ord Mantell changed my mind.LEIA:Han, we need you! DECK OFFICER:Sir, Commander Skywalker hasn't come in through the south entrance. Hemight have forgotten to check in. HAN:It isn't friendly, whatever it is.Come on, Chewie, let's check it out`,
  `EXT. SPACE - IMPERIAL STAR DESTROYER 41 A huge Imperial Star Destroyer rest against a sea of stars,far above the white surface of the planet Hoth.42 INT. IMPERIAL STAR DESTROYER - BRIDGE 42 An Imperial controller approaches his commander.
  CONTROLLER Sir, Rebel ships are coming intour sector.CAPTAIN Good. Our first catch of the day`,
];

export default script;
